spring:
  config:
    activate:
      on-profile: test
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        sale-out:
          destination: ChatResult
          contentType: application/json
        history-out:
          destination: ChattingHistory
          contentType: application/json
  redis:
    host: localhost
    port: 6379
    password: qT6tDPgpgl
  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false